In [508]:
import pandas as pd

In [509]:
df = pd.read_parquet(r"C:\Users\AaronWork\Projects\LoLTracker\apps\data\test_data.parquet")

In [510]:
pd.set_option('display.max_rows', 15)
pd.set_option('display.max_columns', None)
# pd.reset_option('display.max_rows')
# pd.reset_option('display.max_columns')

In [511]:
df.head()

,matchId,gameCreation,gameDuration,gameVersion,laneOpponent,kills,deaths,assists,championName,firstBloodAssist,firstBloodKill,firstTowerAssist,firstTowerKill,gameEndedInEarlySurrender,gameEndedInSurrender,goldEarned,magicDamageDealtToChampions,physicalDamageDealtToChampions,teamEarlySurrendered,teamPosition,timePlayed,totalDamageDealtToChampions,wardsKilled,wardsPlaced,win,teamId,bluePickTop,bluePickJungle,bluePickMiddle,bluePickBottom,bluePickSupport,redPickTop,redPickJungle,redPickMiddle,redPickBottom,redPickSupport,blueBanTop,blueBanJungle,blueBanMiddle,blueBanBottom,blueBanSupport,redBanTop,redBanJungle,redBanMiddle,redBanBottom,redBanSupport
0,KR_6802398237,1700252146951,1310,13.22.541.9804,Jayce,2,2,4,Orianna,False,False,False,False,False,False,8406,10133,632,False,MIDDLE,1310,10766,2,9,True,100,Varus,MonkeyKing,Orianna,Caitlyn,Morgana,Singed,Nidalee,Jayce,Jhin,Nautilus,Akali,Ziggs,Yone,Kalista,Sylas,Ashe,Draven,Gangplank,Evelynn,Nilah
1,KR_6802385080,1700249925191,1741,13.22.541.9804,Gragas,1,4,21,Alistar,True,False,False,False,False,False,7926,6097,1066,False,UTILITY,1741,8364,4,29,True,200,Riven,LeeSin,Katarina,Kalista,Gragas,Sett,Karthus,Irelia,Jinx,Alistar,JarvanIV,Renekton,Yasuo,Ziggs,Yone,Rakan,Akali,NoBan,KSante,Talon
2,KR_6802359571,1700247753480,1279,13.22.541.9804,Neeko,5,5,2,Xerath,False,True,False,False,False,True,8471,9777,719,False,MIDDLE,1279,10497,3,7,True,100,KSante,Khazix,Xerath,Jinx,Thresh,Ahri,LeeSin,Neeko,Varus,Zilean,NoBan,Akali,Kalista,Ziggs,Taliyah,Yone,Rakan,Kaisa,Orianna,Graves
3,KR_6802338227,1700245628959,1799,13.22.541.9804,Akshan,2,7,11,Syndra,False,False,False,False,False,True,12297,24226,511,False,MIDDLE,1799,26209,1,12,False,200,Vladimir,JarvanIV,Akshan,Xayah,Blitzcrank,Poppy,LeeSin,Syndra,Jhin,Nautilus,Thresh,KSante,Orianna,Kalista,Taliyah,Tryndamere,Yone,Samira,Rumble,Senna
4,KR_6802300416,1700243397489,1773,13.22.541.9804,KSante,8,8,5,Gragas,False,False,False,False,False,False,12134,25104,1726,False,TOP,1773,26850,1,12,False,100,Gragas,Graves,Yasuo,Ezreal,Nautilus,KSante,Brand,Tryndamere,Varus,Karma,Leblanc,Blitzcrank,Draven,Yone,Aatrox,Akali,Kalista,Ziggs,NoBan,Nidalee

In [512]:
import numpy as np

# Add a new column 'Side' based on conditions
df['sideWin'] = np.where((df['win'] & (df['teamId'] == 100)) | (~df['win'] & (df['teamId'] == 200)), 'blueSide', 'redSide')

# Print the DataFrame with the new column
df

,matchId,gameCreation,gameDuration,gameVersion,laneOpponent,kills,deaths,assists,championName,firstBloodAssist,firstBloodKill,firstTowerAssist,firstTowerKill,gameEndedInEarlySurrender,gameEndedInSurrender,goldEarned,magicDamageDealtToChampions,physicalDamageDealtToChampions,teamEarlySurrendered,teamPosition,timePlayed,totalDamageDealtToChampions,wardsKilled,wardsPlaced,win,teamId,bluePickTop,bluePickJungle,bluePickMiddle,bluePickBottom,bluePickSupport,redPickTop,redPickJungle,redPickMiddle,redPickBottom,redPickSupport,blueBanTop,blueBanJungle,blueBanMiddle,blueBanBottom,blueBanSupport,redBanTop,redBanJungle,redBanMiddle,redBanBottom,redBanSupport,sideWin
0,KR_6802398237,1700252146951,1310,13.22.541.9804,Jayce,2,2,4,Orianna,False,False,False,False,False,False,8406,10133,632,False,MIDDLE,1310,10766,2,9,True,100,Varus,MonkeyKing,Orianna,Caitlyn,Morgana,Singed,Nidalee,Jayce,Jhin,Nautilus,Akali,Ziggs,Yone,Kalista,Sylas,Ashe,Draven,Gangplank,Evelynn,Nilah,blueSide
1,KR_6802385080,1700249925191,1741,13.22.541.9804,Gragas,1,4,21,Alistar,True,False,False,False,False,False,7926,6097,1066,False,UTILITY,1741,8364,4,29,True,200,Riven,LeeSin,Katarina,Kalista,Gragas,Sett,Karthus,Irelia,Jinx,Alistar,JarvanIV,Renekton,Yasuo,Ziggs,Yone,Rakan,Akali,NoBan,KSante,Talon,redSide
2,KR_6802359571,1700247753480,1279,13.22.541.9804,Neeko,5,5,2,Xerath,False,True,False,False,False,True,8471,9777,719,False,MIDDLE,1279,10497,3,7,True,100,KSante,Khazix,Xerath,Jinx,Thresh,Ahri,LeeSin,Neeko,Varus,Zilean,NoBan,Akali,Kalista,Ziggs,Taliyah,Yone,Rakan,Kaisa,Orianna,Graves,blueSide
3,KR_6802338227,1700245628959,1799,13.22.541.9804,Akshan,2,7,11,Syndra,False,False,False,False,False,True,12297,24226,511,False,MIDDLE,1799,26209,1,12,False,200,Vladimir,JarvanIV,Akshan,Xayah,Blitzcrank,Poppy,LeeSin,Syndra,Jhin,Nautilus,Thresh,KSante,Orianna,Kalista,Taliyah,Tryndamere,Yone,Samira,Rumble,Senna,blueSide
4,KR_6802300416,1700243397489,1773,13.22.541.9804,KSante,8,8,5,Gragas,False,False,False,False,False,False,12134,25104,1726,False,TOP,1773,26850,1,12,False,100,Gragas,Graves,Yasuo,Ezreal,Nautilus,KSante,Brand,Tryndamere,Varus,Karma,Leblanc,Blitzcrank,Draven,Yone,Aatrox,Akali,Kalista,Ziggs,NoBan,Nidalee,redSide
5,KR_6802262157,1700241209034,1828,13.22.541.9804,TwistedFate,9,5,10,Viktor,False,False,False,False,False,True,13909,38172,491,False,MIDDLE,1828,38663,1,12,True,100,Fiora,LeeSin,Viktor,Varus,Senna,Rumble,Vi,TwistedFate,Nilah,Zilean,Neeko,NoBan,Kennen,Akali,Kalista,Ashe,Ziggs,Sylas,Kalista,Graves,blueSide
6,KR_6802199102,1700238803739,1699,13.22.541.9804,Thresh,2,9,9,Alistar,False,False,False,False,False,False,6856,5569,1215,False,UTILITY,1699,7749,6,33,False,100,Akali,Vi,Ahri,Draven,Alistar,Fiora,Graves,Taliyah,Varus,Thresh,Rakan,Ziggs,JarvanIV,Rumble,Syndra,Blitzcrank,Kalista,Kaisa,Jax,Orianna,redSide
7,KR_6802124922,1700236715724,1581,13.22.541.9804,Orianna,5,4,4,Syndra,False,False,False,False,False,True,12634,13559,370,False,MIDDLE,1581,15440,1,11,True,100,Rumble,Graves,Syndra,Varus,Senna,Tryndamere,MonkeyKing,Orianna,Xayah,Rakan,Draven,Akali,Taliyah,Rell,JarvanIV,KSante,Kalista,Jax,Draven,Zed,blueSide
8,KR_6802047324,1700234490855,1737,13.22.541.9804,Syndra,4,2,3,Orianna,False,False,False,False,False,False,10560,24783,1471,False,MIDDLE,1737,26309,6,13,False,200,Rumble,JarvanIV,Syndra,Draven,Rell,Ryze,LeeSin,Orianna,Varus,Rakan,NoBan,Ziggs,Caitlyn,Xayah,Yone,Akali,Ziggs,Karthus,Kalista,Fiora,blueSide
9,KR_6800708990,1700174944722,1718,13.22.541.9804,Poppy,4,5,6,Gangplank,False,False,False,False,False,False,16033,1953,13665,False,MIDDLE,1718,21922,0,10,False,100,Jayce,Karthus,Gangplank,Ezreal,Lulu,Rumble,LeeSin,Poppy,Kaisa,Rell,Akali,Nidalee,Kalista,Blitzcrank,Jax,Orianna,Neeko,Akali,NoBan,Jax,redSide

In [513]:
df[["championName", "laneOpponent"]]

  championName laneOpponent
0      Orianna        Jayce
1      Alistar       Gragas
2       Xerath        Neeko
3       Syndra       Akshan
4       Gragas       KSante
5       Viktor  TwistedFate
6      Alistar       Thresh
7       Syndra      Orianna
8      Orianna       Syndra
9    Gangplank        Poppy

In [514]:
df[["bluePickTop", "bluePickJungle", "bluePickMiddle", "bluePickBottom", "bluePickSupport", "redPickTop", "redPickJungle", "redPickMiddle",
    "redPickBottom", "redPickSupport"]]

,bluePickTop,bluePickJungle,bluePickMiddle,bluePickBottom,bluePickSupport,redPickTop,redPickJungle,redPickMiddle,redPickBottom,redPickSupport
0,Varus,MonkeyKing,Orianna,Caitlyn,Morgana,Singed,Nidalee,Jayce,Jhin,Nautilus
1,Riven,LeeSin,Katarina,Kalista,Gragas,Sett,Karthus,Irelia,Jinx,Alistar
2,KSante,Khazix,Xerath,Jinx,Thresh,Ahri,LeeSin,Neeko,Varus,Zilean
3,Vladimir,JarvanIV,Akshan,Xayah,Blitzcrank,Poppy,LeeSin,Syndra,Jhin,Nautilus
4,Gragas,Graves,Yasuo,Ezreal,Nautilus,KSante,Brand,Tryndamere,Varus,Karma
5,Fiora,LeeSin,Viktor,Varus,Senna,Rumble,Vi,TwistedFate,Nilah,Zilean
6,Akali,Vi,Ahri,Draven,Alistar,Fiora,Graves,Taliyah,Varus,Thresh
7,Rumble,Graves,Syndra,Varus,Senna,Tryndamere,MonkeyKing,Orianna,Xayah,Rakan
8,Rumble,JarvanIV,Syndra,Draven,Rell,Ryze,LeeSin,Orianna,Varus,Rakan
9,Jayce,Karthus,Gangplank,Ezreal,Lulu,Rumble,LeeSin,Poppy,Kaisa,Rell

In [515]:
import pandas as pd

ROLES_PICK_COLUMNS = [
    "bluePickTop", "bluePickJungle", "bluePickMiddle", "bluePickBottom", "bluePickSupport", "redPickTop",
    "redPickJungle", "redPickMiddle", "redPickBottom", "redPickSupport"
]

games_played = df.shape[0]

# Create a Series of sets where each set represents unique bans in a row
unique_champions_picks_per_row = df.apply(lambda row: set(row[ROLES_PICK_COLUMNS]), axis=1)

# Concatenate all sets into a single Series
all_champions_picks = pd.Series([champion for row in unique_champions_picks_per_row for champion in row])

# Calculate cumulative sum for each Champion
cumulative_sum_champions_picks = all_champions_picks.value_counts()

# Create DataFrame with GamesBanned and Banrate
df_picks = pd.DataFrame({"GamesPicked": cumulative_sum_champions_picks, "Pickrate": cumulative_sum_champions_picks / games_played})

# Reset the index to make "ChampionName" a regular column
df_picks = df_picks.reset_index()

# Rename columns if needed
df_picks = df_picks.rename(columns={'index': 'ChampionName'})

# Print or use df_bans as needed
df_picks

   ChampionName  GamesPicked  Pickrate
0         Varus            7       0.7
1        LeeSin            6       0.6
2        Rumble            4       0.4
3        Graves            3       0.3
4      Nautilus            3       0.3
..          ...          ...       ...
51       Xerath            1       0.1
52     Vladimir            1       0.1
53       Akshan            1       0.1
54   Blitzcrank            1       0.1
55        Kaisa            1       0.1

[56 rows x 3 columns]

In [516]:
import pandas as pd

ROLES_BAN_COLUMNS = [
    'blueBanTop', 'blueBanJungle', 'blueBanMiddle', 'blueBanBottom', 'blueBanSupport', 'redBanTop', 'redBanJungle',
    'redBanMiddle', 'redBanBottom', 'redBanSupport'
]

games_played = df.shape[0]

# Create a Series of sets where each set represents unique bans in a row
unique_champions_bans_per_row = df.apply(lambda row: set(row[ROLES_BAN_COLUMNS]), axis=1)

# Concatenate all sets into a single Series
all_champions_bans = pd.Series([champion for row in unique_champions_bans_per_row for champion in row])

# Calculate cumulative sum for each Champion
cumulative_sum_champions_bans = all_champions_bans.value_counts()

# Create DataFrame with GamesBanned and Banrate
df_bans = pd.DataFrame({"GamesBanned": cumulative_sum_champions_bans, "Banrate": cumulative_sum_champions_bans / games_played})

# Reset the index to make "ChampionName" a regular column
df_bans = df_bans.reset_index()

df_bans = df_bans.rename(columns={'index': 'ChampionName'})

df_bans

   ChampionName  GamesBanned  Banrate
0       Kalista            9      0.9
1         Akali            8      0.8
2         Ziggs            7      0.7
3         NoBan            6      0.6
4          Yone            6      0.6
..          ...          ...      ...
35   Tryndamere            1      0.1
36       Thresh            1      0.1
37       Samira            1      0.1
38        Talon            1      0.1
39        Xayah            1      0.1

[40 rows x 3 columns]

In [517]:
df_merged = pd.merge(df_picks, df_bans, on='ChampionName', how='left').fillna(0)

df_merged = df_merged.rename(columns={'GamesBanned': 'GamesBanned', 'Banrate': 'Banrate'})

df_merged["Presence"] = df_merged["Pickrate"] + df_merged["Banrate"]

df_merged.sort_values("Presence", ascending=False)

   ChampionName  GamesPicked  Pickrate  GamesBanned  Banrate  Presence
44      Kalista            1       0.1          9.0      0.9       1.0
35        Akali            1       0.1          8.0      0.8       0.9
6       Orianna            3       0.3          4.0      0.4       0.7
0         Varus            7       0.7          0.0      0.0       0.7
2        Rumble            4       0.4          2.0      0.2       0.6
..          ...          ...       ...          ...      ...       ...
45        Riven            1       0.1          0.0      0.0       0.1
32       Viktor            1       0.1          0.0      0.0       0.1
43       Singed            1       0.1          0.0      0.0       0.1
42      Morgana            1       0.1          0.0      0.0       0.1
33  TwistedFate            1       0.1          0.0      0.0       0.1

[56 rows x 6 columns]

In [518]:
df[ROLES_PICK_COLUMNS + ["sideWin"]]

,bluePickTop,bluePickJungle,bluePickMiddle,bluePickBottom,bluePickSupport,redPickTop,redPickJungle,redPickMiddle,redPickBottom,redPickSupport,sideWin
0,Varus,MonkeyKing,Orianna,Caitlyn,Morgana,Singed,Nidalee,Jayce,Jhin,Nautilus,blueSide
1,Riven,LeeSin,Katarina,Kalista,Gragas,Sett,Karthus,Irelia,Jinx,Alistar,redSide
2,KSante,Khazix,Xerath,Jinx,Thresh,Ahri,LeeSin,Neeko,Varus,Zilean,blueSide
3,Vladimir,JarvanIV,Akshan,Xayah,Blitzcrank,Poppy,LeeSin,Syndra,Jhin,Nautilus,blueSide
4,Gragas,Graves,Yasuo,Ezreal,Nautilus,KSante,Brand,Tryndamere,Varus,Karma,redSide
5,Fiora,LeeSin,Viktor,Varus,Senna,Rumble,Vi,TwistedFate,Nilah,Zilean,blueSide
6,Akali,Vi,Ahri,Draven,Alistar,Fiora,Graves,Taliyah,Varus,Thresh,redSide
7,Rumble,Graves,Syndra,Varus,Senna,Tryndamere,MonkeyKing,Orianna,Xayah,Rakan,blueSide
8,Rumble,JarvanIV,Syndra,Draven,Rell,Ryze,LeeSin,Orianna,Varus,Rakan,blueSide
9,Jayce,Karthus,Gangplank,Ezreal,Lulu,Rumble,LeeSin,Poppy,Kaisa,Rell,redSide

In [519]:
import pandas as pd

blue_side_values = df[df["sideWin"] == "blueSide"]
blue_side_values
blue_columns = blue_side_values.filter(like='bluePick', axis=1)
blue_columns

  bluePickTop bluePickJungle bluePickMiddle bluePickBottom bluePickSupport
0       Varus     MonkeyKing        Orianna        Caitlyn         Morgana
2      KSante         Khazix         Xerath           Jinx          Thresh
3    Vladimir       JarvanIV         Akshan          Xayah      Blitzcrank
5       Fiora         LeeSin         Viktor          Varus           Senna
7      Rumble         Graves         Syndra          Varus           Senna
8      Rumble       JarvanIV         Syndra         Draven            Rell

In [520]:
df_melted_blue = pd.melt(blue_columns, value_vars=blue_columns.columns)
blue_side_champion_wins = df_melted_blue['value'].value_counts()

blue_side_champion_wins

value
Varus         3
Senna         2
Rumble        2
JarvanIV      2
Syndra        2
             ..
Khazix        1
MonkeyKing    1
Fiora         1
Vladimir      1
Rell          1
Name: count, Length: 24, dtype: int64

In [521]:
import pandas as pd

red_side_values = df[df["sideWin"] == "redSide"]
red_side_values
red_columns = red_side_values.filter(like='redPick', axis=1)
red_columns

  redPickTop redPickJungle redPickMiddle redPickBottom redPickSupport
1       Sett       Karthus        Irelia          Jinx        Alistar
4     KSante         Brand    Tryndamere         Varus          Karma
6      Fiora        Graves       Taliyah         Varus         Thresh
9     Rumble        LeeSin         Poppy         Kaisa           Rell

In [522]:
df_melted_red = pd.melt(red_columns, value_vars=red_columns.columns)
red_side_champion_wins = df_melted_red['value'].value_counts()

red_side_champion_wins

value
Varus      2
Sett       1
Taliyah    1
Thresh     1
Karma      1
          ..
Brand      1
Karthus    1
Rumble     1
Fiora      1
Rell       1
Name: count, Length: 19, dtype: int64

In [523]:
result = blue_side_champion_wins.add(red_side_champion_wins, fill_value=0).sort_values(ascending=False).astype(int)
result

value
Varus         5
Rumble        3
Jinx          2
JarvanIV      2
Senna         2
             ..
Draven        1
Caitlyn       1
Brand         1
Blitzcrank    1
Xerath        1
Name: count, Length: 34, dtype: int32

In [524]:
df[ROLES_PICK_COLUMNS]

,bluePickTop,bluePickJungle,bluePickMiddle,bluePickBottom,bluePickSupport,redPickTop,redPickJungle,redPickMiddle,redPickBottom,redPickSupport
0,Varus,MonkeyKing,Orianna,Caitlyn,Morgana,Singed,Nidalee,Jayce,Jhin,Nautilus
1,Riven,LeeSin,Katarina,Kalista,Gragas,Sett,Karthus,Irelia,Jinx,Alistar
2,KSante,Khazix,Xerath,Jinx,Thresh,Ahri,LeeSin,Neeko,Varus,Zilean
3,Vladimir,JarvanIV,Akshan,Xayah,Blitzcrank,Poppy,LeeSin,Syndra,Jhin,Nautilus
4,Gragas,Graves,Yasuo,Ezreal,Nautilus,KSante,Brand,Tryndamere,Varus,Karma
5,Fiora,LeeSin,Viktor,Varus,Senna,Rumble,Vi,TwistedFate,Nilah,Zilean
6,Akali,Vi,Ahri,Draven,Alistar,Fiora,Graves,Taliyah,Varus,Thresh
7,Rumble,Graves,Syndra,Varus,Senna,Tryndamere,MonkeyKing,Orianna,Xayah,Rakan
8,Rumble,JarvanIV,Syndra,Draven,Rell,Ryze,LeeSin,Orianna,Varus,Rakan
9,Jayce,Karthus,Gangplank,Ezreal,Lulu,Rumble,LeeSin,Poppy,Kaisa,Rell

In [529]:
# Extract champion columns
champion_columns = df[ROLES_PICK_COLUMNS]

# Concatenate all champion columns into a single Series
all_champions = pd.Series(df[ROLES_PICK_COLUMNS].values.flatten())

# Count the occurrences of each champion
champion_appearances = all_champions.value_counts()

df1 = pd.DataFrame({'ChampionName': champion_appearances.index, 'ChampionGames': champion_appearances.values})
df2 = pd.DataFrame({'ChampionName': result.index, 'ChampionWins': result.values.astype(int)})

merged_df_winrate = pd.merge(df1, df2, on='ChampionName', how='outer').fillna(0)
merged_df_winrate["Winrate"] = merged_df_winrate["ChampionWins"] / merged_df_winrate["ChampionGames"]
merged_df_winrate
# df2 = pd.DataFrame({'ChampionName': series2.index, 'Count2': series2.values})
#merged_df = pd.merge(champion_appearances, result, on='ChampionName', how='outer').fillna(0)

df_merged = pd.merge(df_picks, df_bans, on='ChampionName', how='left').fillna(0)

df_merged = df_merged.rename(columns={'GamesBanned': 'GamesBanned', 'Banrate': 'Banrate'})

df_merged["Presence"] = df_merged["Pickrate"] + df_merged["Banrate"]

df_merged.sort_values("Presence", ascending=False)

merged_merged = pd.merge(df_merged, merged_df_winrate[["ChampionName", "ChampionWins", "Winrate"]], on="ChampionName", how="outer").fillna(0)

merged_merged

,ChampionName,GamesPicked,Pickrate,GamesBanned,Banrate,Presence,Winrate
0,Varus,7,0.7,0.0,0.0,0.7,0.714286
1,LeeSin,6,0.6,0.0,0.0,0.6,0.333333
2,Rumble,4,0.4,2.0,0.2,0.6,0.750000
3,Graves,3,0.3,2.0,0.2,0.5,0.666667
4,Nautilus,3,0.3,0.0,0.0,0.3,0.000000
...,...,...,...,...,...,...,...
51,Xerath,1,0.1,0.0,0.0,0.1,1.000000
52,Vladimir,1,0.1,0.0,0.0,0.1,1.000000
53,Akshan,1,0.1,0.0,0.0,0.1,1.000000
54,Blitzcrank,1,0.1,3.0,0.3,0.4,1.000000
55,Kaisa,1,0.1,2.0,0.2,0.3,1.000000